language: c
sudo: false
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
install:
  - arduino --install-library "Adafruit SleepyDog Library,Adafruit FONA Library,Adafruit CC3000 Library,Adafruit AM2315"
script:
  - arduino --board arduino:avr:uno --save-prefs
  - arduino --verify $PWD/arduino-cc3000/analog-in/analog-in.ino
  - arduino --verify $PWD/arduino-cc3000/analog-out/analog-out.ino
  - arduino --verify $PWD/arduino-cc3000/digital-in/digital-in.ino
  - arduino --verify $PWD/arduino-cc3000/digital-out/digital-out.ino
  - arduino --verify $PWD/arduino-cc3000/group-sensor/group-sensor.ino
  - arduino --verify $PWD/arduino-fona/analog-in/analog-in.ino
  - arduino --verify $PWD/arduino-fona/analog-out/analog-out.ino
  - arduino --verify $PWD/arduino-fona/digital-in/digital-in.ino
  - arduino --verify $PWD/arduino-fona/digital-out/digital-out.ino
  - arduino --verify $PWD/arduino-fona/gps/gps.ino
  - arduino --verify $PWD/arduino-fona/group-sensor/group-sensor.ino
  - arduino --board esp8266:esp8266:generic --save-prefs
  - arduino --verify $PWD/esp8266/analog-in/analog-in.ino
  - arduino --verify $PWD/esp8266/analog-out/analog-out.ino
  - arduino --verify $PWD/esp8266/digital-in/digital-in.ino
  - arduino --verify $PWD/esp8266/digital-out/digital-out.ino
  - arduino --verify $PWD/esp8266/group-sensor/group-sensor.ino
notifications:
  email:
    on_success: change
    on_failure: change
